/**
 * Message keys used by the lead deck (`deck-presentation.tsx`) — docs / Excel export only.
 * Order follows slide flow (hero → closing). Format: `Namespace.key` (next-intl paths).
 */
export const DECK_MESSAGE_KEYS = [
  // Slide 1 — Hero
  "Home.heroKicker",
  "Home.heroHeadline",
  "Home.heroSubheadline",
  // Slide 2 — Welcome
  "Home.welcomeP1",
  "Home.deckWelcomeP2",
  "Home.welcomeP3",
  "Home.outcome2ImageAlt",
  // Slide 3 — Two paths
  "Home.twoPathsTitle",
  "Home.twoPathsCard1Tag",
  "Home.twoPathsCard1Title",
  "Home.twoPathsCard1ForPractice",
  "Home.twoPathsCard1ForClients",
  "Home.twoPathsCard2Tag",
  "Home.twoPathsCard2Title",
  "Home.twoPathsCard2ForPractice",
  "Home.twoPathsCard2ForClients",
  "Home.twoPathsMicroPracticeLabel",
  "Home.twoPathsMicroPatientsLabel",
  // Slide 4 — Three technologies
  "HowItWorks.block2Title",
  "HowItWorks.block2Lead",
  "HowItWorks.block3Item1Title",
  "HowItWorks.block3Item1Body",
  "HowItWorks.block3Item2Title",
  "HowItWorks.block3Item2Body",
  "HowItWorks.block3Item3Title",
  "HowItWorks.block3Item3Body",
  // Slide 5 — System
  "Home.systemTitle",
  "Home.systemLead",
  "Home.systemBullet1Title",
  "Home.systemBullet1Body",
  "Home.systemBullet2Title",
  "Home.systemBullet2Body",
  "Home.systemBullet3Title",
  "Home.systemBullet3Body",
  "Home.systemBullet4Title",
  "Home.systemBullet4Body",
  "Home.systemImageAlt",
  "Home.systemProductLabelGen",
  "Home.systemProductLabelMat",
  "Home.systemProductLabelPad",
  "Home.systemProductLabelPen",
  // Slide 6 — Outcomes (4 tiles)
  "Home.outcomesTitle",
  "Home.outcomesLead",
  "Home.outcome1Title",
  "Home.outcome1ForClients",
  "Home.outcome1ImageAlt",
  "Home.outcome2Title",
  "Home.outcome2ForClients",
  "Home.outcome3Title",
  "Home.outcome3ForClients",
  "Home.outcome3ImageAlt",
  "Home.outcome4Title",
  "Home.outcome4ForClients",
  "Home.outcome4ImageAlt",
  // Slides 7–9 — Tech deep-dives
  "HowItWorks.tech1Kicker",
  "HowItWorks.tech1Title",
  "HowItWorks.tech1WhatIsLabel",
  "HowItWorks.tech1WhatIs",
  "HowItWorks.tech1ScienceLabel",
  "HowItWorks.tech1Science",
  "HowItWorks.tech2Kicker",
  "HowItWorks.tech2Title",
  "HowItWorks.tech2WhatIsLabel",
  "HowItWorks.tech2WhatIs",
  "HowItWorks.tech2ScienceLabel",
  "HowItWorks.tech2Science",
  "HowItWorks.tech3Kicker",
  "HowItWorks.tech3Title",
  "HowItWorks.tech3WhatIsLabel",
  "HowItWorks.tech3WhatIs",
  "HowItWorks.tech3ScienceLabel",
  "HowItWorks.tech3Science",
  // Slide 10 — Rollout
  "Home.rolloutTitle",
  "Home.rolloutLead",
  "Home.rolloutWeeksIntro",
  "Home.rolloutStep1Title",
  "Home.rolloutStep1Detail",
  "Home.rolloutStep2Title",
  "Home.rolloutStep2Detail",
  "Home.rolloutStep3Title",
  "Home.rolloutStep3Detail",
  "Home.rolloutStep4Title",
  "Home.rolloutStep4Detail",
  // Slide 11 — Closing
  "Home.deckClosingKicker",
  "Home.deckYourContactLabel",
  "HowItWorks.ctaTitle",
  "HowItWorks.ctaBody",
  "HowItWorks.closingWebsiteLabel",
  "HowItWorks.closingWebsiteDisplay",
  "Contact.email",
  "Contact.companyEmail",
  "Contact.phone",
  "Contact.companyPhone",
] as const;

export type DeckMessageKey = (typeof DECK_MESSAGE_KEYS)[number];
